### ISSUE TITLE
changing default language not working

### ISSUE THREAD

**Issue by francisco-core** [Xzya/hugo-bootstrap#11]
When changed in the config file
defaultContentLanguage = "en" to defaultContentLanguage = "es"
Nothing happens. The default website is all still in english

**Comment by Xzya** [comment]
Hey,

You're right. The location of the `defaultContentLanguage` was wrong in the exampleSite.
I fixed it in [this](https://github.com/Xzya/hugo-bootstrap/commit/6003e25c95e5a5c580dce2521ef5014f56ceb172) commit.

Let me know if this fixes your problem,
Thank you!

**Comment by francisco-core** [comment]
Excellent! Thanks for the quick response and for working on this awesome theme.
I'd been looking for a fix for a while but something so obvious like it being under "[taxonomy]" never occurred to me. I guess have to get a little more familiar with .toml files.

It did fix the problem!
Many Thanks!

**Comment by francisco-core** [comment]
Thanks for also fixing it in your other repo :+1:
