### ISSUE TITLE
Hugo Bootstrap Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [Xzya/hugo-bootstrap#29]
Hello @Xzya 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \hugo-bootstrap\exampleSite\config.toml:
        # Google analytics
        googleAnalytics = "UA-47268287-3"
```

To fix this issue please leave the above parameter blank i.e.

```
     \hugo-bootstrap\exampleSite\config.toml:
        # Google analytics
        googleAnalytics = ""
```

Once you look into this please let me know.

Thank you!

**Comment by Xzya** [comment]
Hello @onedrawingperday,

I [commented out](https://github.com/Xzya/hugo-bootstrap/commit/52feb110977a53bc36fe09868fbbc7d1d4c8cb29#diff-991d2a2fe208cdee83955ad6e9a323a7R18) the Google Analytics ID here as well.

Thanks!

**Comment by onedrawingperday** [comment]
Thanks @Xzya 👍
